### ISSUE TITLE
feat: relax `typer` requirement constraints

### ISSUE THREAD

**Issue by davidberenstein1957** [DS4SD/deepsearch-toolkit#143]
The enforced `typer` constraints `typer<0.5.0 and >=0.4.0` seem a bit restrictive and don't allow installing it i.c.m. argilla.

**Comment by dolfim-ibm** [comment]
I was just looking it up, we have already `typer=^0.9.0`, https://github.com/DS4SD/deepsearch-toolkit/blob/main/pyproject.toml#L43

**Comment by dolfim-ibm** [comment]
@davidberenstein1957 is this still an issue?

**Comment by davidberenstein1957** [comment]
It is not at the moment but if there are no major differences setting `typer` to something like `typer>=0.7.0,typer<1` might give some bandwidth when installing with other packages.
