### ISSUE TITLE
auth key in DeepSearchConfig gets replaced at instantiation of CpsApiClient

### ISSUE THREAD

**Issue by agiova** [DS4SD/deepsearch-toolkit#36]
This issue is about the following lines: https://github.com/DS4SD/deepsearch-toolkit/blob/main/deepsearch/cps/client/api.py#L26-L35

There, `DeepSearchKeyAuth` in `config.auth` is replaced with `DeepSearchBearerTokenAuth`, instead of maintaining the former. In addition, as in line 26 the config dictionary is only referenced, config is modified also outside the class instantiation.

I would suggest to add a key for bearer_token_auth in self.config and not change the config file accessible outside of the class.

**Comment by dolfim-ibm** [comment]
Fixed in https://github.com/DS4SD/deepsearch-toolkit/releases/tag/v0.3.4
