### ISSUE TITLE
HTTP 404 Error when trying to instantiate a ConversionSettings object

### ISSUE THREAD

**Issue by timurcarstensen** [DS4SD/deepsearch-toolkit#65]
**What happened + What you expected to happen**

I followed the [user guide](https://ds4sd.github.io/deepsearch-toolkit/guide/convert_doc/#customize-conversion-settings) for modifying the document conversion settings. When trying to instantiate a ConversionSettings object, I get the following error:

```
Traceback (most recent call last):
  File "/home/timurcarstensen/EFSA/src/debugging_reproduction.py", line 23, in <module>
    conv_settings = ConversionSettings.from_defaults(api=api)
  File "/home/timurcarstensen/miniconda3/envs/efsa3.9/lib/python3.9/site-packages/deepsearch/documents/core/models.py", line 333, in from_defaults
    request_conv_settings.raise_for_status()
  File "/home/timurcarstensen/miniconda3/envs/efsa3.9/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://deepsearch-experience.res.ibm.com/api/linked-ccs/public/v4/settings/conversion_defaults
```

**Versions / Dependencies**
deepsearch-toolkit 0.10.1 
python 3.11
OS Ubuntu through WSL2

**Reproduction script**
import deepsearch as ds
from deepsearch.documents.core.models import ConversionSettings

with open('api_key') as f:
    api_key=f.readline()

auth = ds.DeepSearchKeyAuth(username="EMAIL", api_key=api_key)
config = ds.DeepSearchConfig(host="https://deepsearch-experience.res.ibm.com", auth=auth)
client = ds.CpsApiClient(config)
api = ds.CpsApi(client)

conv_settings = ConversionSettings.from_defaults(api=api)

**What have you tried to resolve the issue?**
- Installing prior versions of the toolkit
- Downgrading to a less recent python version (3.9)
- Installing from source

**Comment by dolfim-ibm** [comment]
Hi @timurcarstensen, the conversion settings are currently available only on the internal systems. The public open access instance of our Deep Search experience allows only the usage of the default settings.

If you let us know your use case, we might be able to assist you onboarding on other systems.
